GET https://api.calendly.com/group_relationships
Authorization: Bearer eyJraWQiOiIxY2UxZTEzNjE3ZGNmNzY2YjNjZWJjY2Y4ZGM1YmFmYThhNjVlNjg0MDIzZjdjMzJiZTgzNDliMjM4MDEzNWI0IiwidHlwIjoiUEFUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2F1dGguY2FsZW5kbHkuY29tIiwiaWF0IjoxNzQ5MDY4OTY3LCJqdGkiOiJjZTNmYjc1ZC1lZWRmLTRkMDktODZhZC1kNzM5ZTYzMTJhZmEiLCJ1c2VyX3V1aWQiOiI5ZmI0MGJlMi1hZGUwLTQ2NzMtOTc4Yi1jMWNjMDljMTQ1NjAifQ.LMo9Em8U573Vkpa_eQ0VCqOjjrxj8ZDtZRmL7dwZoTfqdp5OGZf3XYiF4F0r7YxwWDbdl9BuhtOQfNgO3FvZAQ
content-type: application/json

{
	"organization": "https://api.calendly.com/organizations/5254f580-2bb6-4175-8ea4-a390dc323d64"
}

####

GET https://api.calendly.com/group_relationships?count=20&organization=https://api.calendly.com/organizations/5254f580-2bb6-4175-8ea4-a390dc323d64
Authorization: Bearer eyJraWQiOiIxY2UxZTEzNjE3ZGNmNzY2YjNjZWJjY2Y4ZGM1YmFmYThhNjVlNjg0MDIzZjdjMzJiZTgzNDliMjM4MDEzNWI0IiwidHlwIjoiUEFUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2F1dGguY2FsZW5kbHkuY29tIiwiaWF0IjoxNzQ5MDY4OTY3LCJqdGkiOiJjZTNmYjc1ZC1lZWRmLTRkMDktODZhZC1kNzM5ZTYzMTJhZmEiLCJ1c2VyX3V1aWQiOiI5ZmI0MGJlMi1hZGUwLTQ2NzMtOTc4Yi1jMWNjMDljMTQ1NjAifQ.LMo9Em8U573Vkpa_eQ0VCqOjjrxj8ZDtZRmL7dwZoTfqdp5OGZf3XYiF4F0r7YxwWDbdl9BuhtOQfNgO3FvZAQ
Accept: application/json
